version: '3.9'

services:
  spring:
    build: .
    container_name: spring-server

    ports:
      - "8080:8080"

    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: campus-mysql

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: campuspolio

    ports:
      - "3307:3306"

    command:
      --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    container_name: campus-redis

    ports:
      - "6380:6379"