version: "3.8"

services:
  backend:
    env_file:
      - .env
    build: .
    container_name: campus-backend

    depends_on:
      - redis

    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_ENDPOINT: redis
      REDIS_PORT: 6379

      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >
        -Dsun.net.inetaddr.ttl=0
        -Dsun.net.inetaddr.negative.ttl=0

    ports:
      - "8080:8080"

    restart: always

  redis:
    image: redis:7
    container_name: campus-redis

    ports:
      - "6379:6379"

    restart: always