version: '3.9'

services:

  redis:
    image: redis:7
    container_name: campus-redis

    ports:
      - "6379:6379"

  backend:
    image: pokowoo/campuspolio:latest
    container_name: campus-backend

    depends_on:
      - redis

    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

    ports:
      - "8080:8080"