spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campuspolio?serverTimezone=Asia/Seoul
    username: root
    password: 1111

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:dummy-client-id}

logging:
  level:
    org.hibernate.SQL: debug
cloud:
  aws:
    region: ${AWS_REGION}

    s3:
      bucket: ${AWS_S3_BUCKET}

    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}