spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/campuspolio?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6380

  session:
    store-type: redis

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:}

logging:
  level:
    org.hibernate.SQL: debug