name: Deploy Spring Boot

on:
  push:
    branches:
      - feature/projectt

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: GitHub 코드 가져오기
        uses: actions/checkout@v4

      - name: Java 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: gradle build
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Docker 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/campuspolio:latest .

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/campuspolio:latest

      - name: EC2 자동배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/CampusPolio

            sudo docker compose down

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/campuspolio:latest

            sudo docker compose up -d